package Modelo;
// Generated 24/04/2016 03:50:29 PM by Hibernate Tools 4.3.1



/**
 * Creacion generated by hbm2java
 */
public class Creacion  implements java.io.Serializable {


     private int idcreacion;
     private Ruta ruta;
     private Usuario usuario;
     private String pago;
     private Integer calificacion;

    public Creacion() {
    }

	
    public Creacion(int idcreacion) {
        this.idcreacion = idcreacion;
    }
    public Creacion(int idcreacion, Ruta ruta, Usuario usuario, String pago, Integer calificacion) {
       this.idcreacion = idcreacion;
       this.ruta = ruta;
       this.usuario = usuario;
       this.pago = pago;
       this.calificacion = calificacion;
    }
   
    public int getIdcreacion() {
        return this.idcreacion;
    }
    
    public void setIdcreacion(int idcreacion) {
        this.idcreacion = idcreacion;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getPago() {
        return this.pago;
    }
    
    public void setPago(String pago) {
        this.pago = pago;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }




}


