package Modelo;
// Generated 24/04/2016 03:50:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private int idruta;
     private Usuario usuario;
     private String destino;
     private Date fecha;
     private Date hora;
     private int cupo;
     private Set<Creacion> creacions = new HashSet<Creacion>(0);
     private Set<Viaje> viajes = new HashSet<Viaje>(0);

    public Ruta() {
    }

	
    public Ruta(int idruta, String destino, Date fecha, Date hora, int cupo) {
        this.idruta = idruta;
        this.destino = destino;
        this.fecha = fecha;
        this.hora = hora;
        this.cupo = cupo;
    }
    public Ruta(int idruta, Usuario usuario, String destino, Date fecha, Date hora, int cupo, Set<Creacion> creacions, Set<Viaje> viajes) {
       this.idruta = idruta;
       this.usuario = usuario;
       this.destino = destino;
       this.fecha = fecha;
       this.hora = hora;
       this.cupo = cupo;
       this.creacions = creacions;
       this.viajes = viajes;
    }
   
    public int getIdruta() {
        return this.idruta;
    }
    
    public void setIdruta(int idruta) {
        this.idruta = idruta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public int getCupo() {
        return this.cupo;
    }
    
    public void setCupo(int cupo) {
        this.cupo = cupo;
    }
    public Set<Creacion> getCreacions() {
        return this.creacions;
    }
    
    public void setCreacions(Set<Creacion> creacions) {
        this.creacions = creacions;
    }
    public Set<Viaje> getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set<Viaje> viajes) {
        this.viajes = viajes;
    }




}


