package Modelo;
// Generated 24/04/2016 03:50:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String correo;
     private String nombre;
     private String apellido;
     private int passwrd;
     private Set<Viaje> viajes = new HashSet<Viaje>(0);
     private Set<Ruta> rutas = new HashSet<Ruta>(0);
     private Set<Creacion> creacions = new HashSet<Creacion>(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, String correo, String nombre, String apellido, int passwrd) {
        this.idusuario = idusuario;
        this.correo = correo;
        this.nombre = nombre;
        this.apellido = apellido;
        this.passwrd = passwrd;
    }
    public Usuario(int idusuario, String correo, String nombre, String apellido, int passwrd, Set<Viaje> viajes, Set<Ruta> rutas, Set<Creacion> creacions) {
       this.idusuario = idusuario;
       this.correo = correo;
       this.nombre = nombre;
       this.apellido = apellido;
       this.passwrd = passwrd;
       this.viajes = viajes;
       this.rutas = rutas;
       this.creacions = creacions;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getPasswrd() {
        return this.passwrd;
    }
    
    public void setPasswrd(int passwrd) {
        this.passwrd = passwrd;
    }
    public Set<Viaje> getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set<Viaje> viajes) {
        this.viajes = viajes;
    }
    public Set<Ruta> getRutas() {
        return this.rutas;
    }
    
    public void setRutas(Set<Ruta> rutas) {
        this.rutas = rutas;
    }
    public Set<Creacion> getCreacions() {
        return this.creacions;
    }
    
    public void setCreacions(Set<Creacion> creacions) {
        this.creacions = creacions;
    }




}


