package Modelo;
// Generated 24/04/2016 03:50:29 PM by Hibernate Tools 4.3.1



/**
 * ViajeId generated by hbm2java
 */
public class ViajeId  implements java.io.Serializable {


     private Integer idruta;
     private Integer idusuario;

    public ViajeId() {
    }

    public ViajeId(Integer idruta, Integer idusuario) {
       this.idruta = idruta;
       this.idusuario = idusuario;
    }
   
    public Integer getIdruta() {
        return this.idruta;
    }
    
    public void setIdruta(Integer idruta) {
        this.idruta = idruta;
    }
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViajeId) ) return false;
		 ViajeId castOther = ( ViajeId ) other; 
         
		 return ( (this.getIdruta()==castOther.getIdruta()) || ( this.getIdruta()!=null && castOther.getIdruta()!=null && this.getIdruta().equals(castOther.getIdruta()) ) )
 && ( (this.getIdusuario()==castOther.getIdusuario()) || ( this.getIdusuario()!=null && castOther.getIdusuario()!=null && this.getIdusuario().equals(castOther.getIdusuario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdruta() == null ? 0 : this.getIdruta().hashCode() );
         result = 37 * result + ( getIdusuario() == null ? 0 : this.getIdusuario().hashCode() );
         return result;
   }   


}


