package Modelo;
// Generated 24/04/2016 03:50:29 PM by Hibernate Tools 4.3.1



/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private ViajeId id;
     private Ruta ruta;
     private Usuario usuario;

    public Viaje() {
    }

	
    public Viaje(ViajeId id) {
        this.id = id;
    }
    public Viaje(ViajeId id, Ruta ruta, Usuario usuario) {
       this.id = id;
       this.ruta = ruta;
       this.usuario = usuario;
    }
   
    public ViajeId getId() {
        return this.id;
    }
    
    public void setId(ViajeId id) {
        this.id = id;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


